# Generated by Django 4.2.7 on 2024-04-25 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentSwapApp', '0003_alter_vacancyrating_rating_employeerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_experience',
            field=models.IntegerField(default=0, verbose_name='Experiencia laboral en meses'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employeerating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
