# Generated by Django 4.2.7 on 2024-04-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentSwapApp', '0004_employee_work_experience_vacancy_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyrating',
            name='experience',
            field=models.CharField(default=' No comments', max_length=300),
        ),
    ]
