# Generated by Django 4.2.7 on 2024-03-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentSwapApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=300)),
            ],
        ),
    ]
