# Generated by Django 5.0.2 on 2024-03-19 00:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentSwapApp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
