# Generated by Django 4.2.7 on 2024-03-20 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TalentSwapApp', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
