# Generated by Django 4.2.7 on 2024-03-20 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentSwapApp', '0004_vacancy_created_on_alter_vacancy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyvacancy',
            name='title',
            field=models.CharField(default=datetime.datetime(2024, 3, 19, 23, 3, 58, 327041), max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applyvacancy',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
