# Generated by Django 4.2.7 on 2024-03-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentSwapApp', '0005_applyvacancy_title_alter_applyvacancy_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyvacancy',
            old_name='title',
            new_name='vacancy_title',
        ),
    ]
