# Generated by Django 4.2.7 on 2024-03-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentSwapApp', '0006_rename_title_applyvacancy_vacancy_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyvacancy',
            old_name='vacancy_title',
            new_name='title',
        ),
    ]
